Available rides screen added
ACM-VIT/carpoolit-app pull request #31
Opened 2024-01-06 16:35 UTC by manan04shah

Issue fixed: #4 
Changes in this PR:
- Added assets for search and filter button icons
- Added json file for dummy rides data
- Created available rides screen
- Changed name format in ride card to be marquee text

Screenshot of available rides screen:
![WhatsApp Image 2024-01-06 at 21 57 00_6598943d](https://github.com/ACM-VIT/carpoolit-app/assets/74666385/9856c739-4ee8-4e2b-a439-0482c349d605)

2024-01-07 08:16 UTC, RohanKhatua requested changes
Please see review comments - RK

2024-01-07 08:16 UTC, RohanKhatua commented on components/rideCard.tsx
> +    date: any;
Why any? this makes it not typesafe

2024-01-09 07:55 UTC, anandrajaram21 commented on data/availableRides.json
i'm assuming this file will be removed later right? Once the connection to the backend is done

2024-01-09 07:56 UTC, anandrajaram21 requested changes
can you please resolve merge conflicts and the comment

2024-01-09 11:49 UTC, manan04shah commented on data/availableRides.json
yes, all the files in this dir are dummy data for testing.

2024-01-11 12:12 UTC, manan04shah commented
@anandrajaram21 @RohanKhatua sorry for the delay, necessary changes have been made

2024-01-13 11:28 UTC, RohanKhatua approved these changes
LGTM YOLO

2024-01-13 11:28 UTC, merged