added time field input in host ride and join ride pages.
ACM-VIT/carpoolit-app pull request #32
Opened 2024-01-07 08:02 UTC by eshita241

added time field input in host ride and join ride pages, also profile page certain parts are done.

2024-01-07 08:18 UTC, RohanKhatua requested changes
Please see review comments

2024-01-07 08:18 UTC, RohanKhatua commented on components/Time.tsx
change to time_display or something, do not name files after reserved classes

2024-01-08 15:02 UTC, eshita241 commented on components/Time.tsx
okay, changed the name to time_display

2024-01-09 07:53 UTC, anandrajaram21 approved these changes
lgtm

2024-01-09 07:53 UTC, merged