Created App navigation routes
ACM-VIT/carpoolit-app pull request #44
Opened 2024-01-15 18:25 UTC by aastikn

Created navigation routes in the app using stack navigation.
![image](https://github.com/ACM-VIT/carpoolit-app/assets/121819805/f3394195-edb6-4767-9404-93323c70ac32)

2024-01-16 16:50 UTC, RohanKhatua requested changes
see review comms

2024-01-16 16:50 UTC, RohanKhatua commented on components/hostjoinSwitch.tsx
> +          }}
abstract to a different function

2024-01-17 16:00 UTC, anandrajaram21 approved these changes
lgtm

2024-01-17 16:01 UTC, merged

2024-01-30 05:48 UTC, aastikn commented
Resolves #42  : App Routing